os:
  - linux
  - osx
  - windows

language: c

env:
  - BRANCH=0.19.4
  - BRANCH=#4f9366975441be889a8cd4fbfb4e41f6830dc542

matrix:
  exclude:
  # Skip devel on Windows due to choosenim #117
  - os: windows
    env: BRANCH=#4f9366975441be889a8cd4fbfb4e41f6830dc542

cache:
  directories:
    - "$HOME/.choosenim/toolchains/nim-0.19.4"
    - "$HOME/.choosenim/toolchains/nim-#4f9366975441be889a8cd4fbfb4e41f6830dc542"

install:
  - export CHOOSENIM_CHOOSE_VERSION=$BRANCH
  - |
      curl https://raw.githubusercontent.com/dom96/choosenim/master/scripts/choosenim-unix-init.sh -sSf > init.sh
      sh init.sh -y

before_script:
  - export CHOOSENIM_NO_ANALYTICS=1
  - export PATH=$HOME/.nimble/bin:$PATH

script:
  - cd tests
  - nim c -r tester
  - cd ..
  - ./src/nimble install -y

notifications:
  irc: "chat.freenode.net#nimbuild"
